### ISSUE TITLE
assetsys.h Win32_WINNT version

### ISSUE THREAD

**Issue by LiamKarlMitchell** [mattiasgustavsson/libs#31]
Just a recommendation to not muck with the value someone else may have defined use a less than check don't just blindly set it to XP minimum.

```cpp
#if _WIN32_WINNT < 0x0501
    #undef _WIN32_WINNT
    #define _WIN32_WINNT 0x0501 // requires Windows XP minimum
    // 0x0400=Windows NT 4.0, 0x0500=Windows 2000, 0x0501=Windows XP, 0x0502=Windows Server 2003, 0x0600=Windows Vista, 
    // 0x0601=Windows 7, 0x0602=Windows 8, 0x0603=Windows 8.1, 0x0A00=Windows 10
#endif
```

**Comment by DBJDBJ** [comment]
But the combination of runtime and compile-time Windows development issues has to be skillfully navigated on Windows. 

`_WIN32_WINNT`  (and `WINVER`) are the epitome of legacy.  In English: hot mess. Your issue is a good example. 
I might like to remind, that is a compile-time aka building issue. Run time issue is also a graveyard of API's semi-officially abandoned. 

use case: write a console app that will run on all Win versions and show colours where they are available. that might require two or more legacy machines for compiling and testing. The outcome is a question: it that feasible?
